# Upgrade Definitions
air_dash            = "Air Dash"
air_jump            = "Air Jump"
auto_earrings       = "Auto Earrings"
book_of_carrot      = "Book Of Carrot"
bunny_amulet        = "Bunny Amulet"
bunny_strike        = "Bunny Strike"
bunny_whirl         = "Bunny Whirl"
carrot_bomb         = "Carrot Bomb"
charge_ring         = "Charge Ring"
cyber_flower        = "Cyber Flower"
fire_orb            = "Fire Orb"
hammer_roll         = "Hammer Roll"
hammer_wave         = "Hammer Wave"
hourglass           = "Hourglass"
light_orb           = "Light Orb"
max_bracelet        = "Max Bracelet"
nature_orb          = "Nature Orb"
p_hairpin           = "P Hairpin"
piko_hammer         = "Piko Hammer"
quick_barrette      = "Quick Barrette"
plus_necklace       = "Plus Necklace"
rabi_slippers       = "Rabi Slippers"
sliding_powder      = "Sliding Powder"
soul_heart          = "Soul Heart"
speed_boost         = "Speed Boost"
spike_barrier       = "Spike Barrier"
strange_box         = "Strange Box"
super_carrot        = "Super Carrot"
wall_jump           = "Wall Jump"
water_orb           = "Water Orb"

# Magic Definitions
carrot_shooter      = "Carrot Shooter"
chaos_rod           = "Chaos Rod"
explode_shot        = "Explode Shot"
healing_staff       = "Healing Staff"
sunny_beam          = "Sunny Beam"

# Badge Definitions
arm_strength        = "Arm Strength"
armored             = "Armored"
atk_grow            = "Atk Grow"
atk_trade           = "Atk Trade"
auto_trigger        = "Auto Trigger"
blessed             = "Blessed"
carrot_boost        = "Carrot Boost"
cashback            = "Cashback"
crisis_boost        = "Crisis Boost"
def_grow            = "Def Grow"
def_trade           = "Def Trade"
erina_badge         = "Erina Badge"
frame_cancel        = "Frame Cancel"
health_plus         = "Health Plus"
health_surge        = "Health Surge"
health_wager        = "Health Wager"
hex_cancel          = "Hex Cancel"
hitbox_down         = "Hitbox Down"
lucky_seven         = "Lucky Seven"
mana_plus           = "Mana Plus"
mana_surge          = "Mana Surge"
mana_wager          = "Mana Wager"
pure_love           = "Pure Love"
ribbon_badge        = "Ribbon Badge"
self_defense        = "Self Defense"
stamina_plus        = "Stamina Plus"
survival            = "Survival"
top_form            = "Top Form"
tough_skin          = "Tough Skin"
toxic_strike        = "Toxic Strike"
weaken              = "Weaken"

# Collectable Definitions
attack_up           = "Attack Up"
easter_egg          = "Easter Egg"
rumi_donut          = "Rumi Donut"
rumi_cake           = "Rumi Cake"
cocoa_bomb          = "Cocoa Bomb"
gold_carrot         = "Gold Carrot"
hp_up               = "HP Up"
mp_up               = "MP Up"
nothing             = "Nothing"
pack_up             = "Pack Up"
regen_up            = "Regen Up"
pbpb_box            = "Pbpb Box"

# Halloween Definitions
liliths_gift = "Liliths Gift"

# "Is the order a DLC?" Definitions
bunny_clover = "Bunny Clover"
wind_blessing = "Wind Blessing"
fairies_flute = "Fairies Flute"

# Recruit Definitions
ashuri_2            = "Ashuri 2"
cocoa_1             = "Cocoa 1"
kotri_1             = "Kotri 1"
kotri_2             = "Kotri 2"
seana_1             = "Seana 1"
cocoa_recruit       = "Cocoa Recruit"
ashuri_recruit      = "Ashuri Recruit"
rita_recruit        = "Rita Recruit"
cicini_recruit      = "Cicini Recruit"
saya_recruit        = "Saya Recruit"
syaro_recruit       = "Syaro Recruit"
pandora_recruit     = "Pandora Recruit"
nieve_recruit       = "Nieve Recruit"
nixie_recruit       = "Nixie Recruit"
aruraune_recruit    = "Aruraune Recruit"
seana_recruit       = "Seana Recruit"
lilith_recruit      = "Lilith Recruit"
vanilla_recruit     = "Vanilla Recruit"
chocolate_recruit   = "Chocolate Recruit"
kotri_recruit       = "Kotri Recruit"
keke_bunny_recruit  = "Keke Bunny Recruit"
miriam_recruit      = "Miriam Recruit"
rumi_recruit        = "Rumi Recruit"
irisu_recruit       = "Irisu Recruit"

# Glitched Logic
glitched_logic = "Glitched Logic"