
# Regions
# Area 0: Southern Woodland
southern_woodland_region        = "Southern Woodland"
forest_start                    = "Forest Start"
forest_warp                     = "Forest Warp"
forest_east_above_spring        = "Forest East Above Spring"
forest_upper_east               = "Forest Upper East"
forest_upper_riverbank_exit     = "Forest Upper Riverbank Exit"
forest_lower_riverbank_exit     = "Forest Lower Riverbank Exit"
forest_light_orb_room           = "Forest Light Orb Room"
forest_upper_east_egg_ledge     = "Forest Upper East Egg Ledge"
forest_cocoa_room               = "Forest Cocoa Room"
forest_north_hp_up_room         = "Forest North Hp Up Room"
forest_night_toxic_strike       = "Forest Night Toxic Strike"
forest_night_north_east         = "Forest Night North East"
forest_night_west               = "Forest Night West"
forest_night_atk_up_room        = "Forest Night Atk Up Room"
cave_entrance                   = "Cave Entrance"
cave_west                       = "Cave West"
cave_cocoa                      = "Cave Cocoa"
forgotten_cave_2                = "Forgotten Cave 2"
spectral_upper                  = "Spectral Upper"
spectral_mid                    = "Spectral Mid"
spectral_west                   = "Spectral West"
spectral_gap_ledge              = "Spectral Gap Ledge"
spectral_west_egg_room          = "Spectral West Egg Room"
spectral_warp                   = "Spectral Warp"
spectral_cicini_ledge           = "Spectral Cicini Ledge"
spectral_cicini_room            = "Spectral Cicini Room"

# Area 1: Western Coast
western_coast_region            = "Western Coast"
beach_main                      = "Beach Main"
beach_forest_entrance           = "Beach Forest Entrance"
beach_underwater_entrance       = "Beach Underwater Entrance"
beach_volcanic_entrance         = "Beach Volcanic Entrance"
pyramid_main                    = "Pyramid Main"
pyramid_hourglass_room          = "Pyramid Hourglass Room"
pyramid_warp_room               = "Pyramid Warp Room"
pyramid_southwest_room          = "Pyramid Southwest Room"
pyramid_lower                   = "Pyramid Lower"
pyramid_chaos_rod_room          = "Pyramid Chaos Rod Room"
graveyard_top_of_bridge         = "Graveyard Top Of Bridge"
graveyard_main                  = "Graveyard Main"
graveyard_kotri                 = "Graveyard Kotri"
graveyard_upper                 = "Graveyard Upper"
sky_island_main                 = "Sky Island Main"
sky_island_air_dash_room        = "Sky Island Air Dash Room"
sky_island_upper                = "Sky Island Upper"
sky_island_oob                  = "Sky Island Oob"
halloween_upper                 = "Halloween Upper"
halloween_dark_shaft            = "Halloween Dark Shaft"
halloween_central               = "Halloween Central"
halloween_flooded               = "Halloween Flooded"
halloween_pumpkin_hall          = "Halloween Pumpkin Hall"
halloween_exit                  = "Halloween Exit"
halloween_past_pillars          = "Halloween Past Pillars"
library_outside                 = "Library Outside"
library_entrance                = "Library Entrance"
library_bottom                  = "Library Bottom"
library_alcove_ledge            = "Library Alcove Ledge"
library_mid_lower               = "Library Mid Lower"
library_mid_upper               = "Library Mid Upper"
library_irisu                   = "Library Irisu"
library_oob                     = "Library Oob"

# Area 2: Island Core
island_core_region              = "Island Core"
ravine_lower                    = "Ravine Lower"
ravine_upper_east               = "Ravine Upper East"
ravine_upper_west               = "Ravine Upper West"
ravine_mana_surge               = "Ravine Mana Surge"
ravine_north_attack_up_room     = "Ravine North Attack Up Room"
ravine_chocolate                = "Ravine Chocolate"
ravine_above_chocolate          = "Ravine Above Chocolate"
ravine_town_entrance            = "Ravine Town Entrance"
ravine_beach_entrance           = "Ravine Beach Entrance"
park_main                       = "Park Main"
park_warp                       = "Park Warp"
park_kotri                      = "Park Kotri"
park_town_entrance              = "Park Town Entrance"
park_upper                      = "Park Upper"
uprprc_base                     = "Uprprc Base"
uprprc_lower                    = "Uprprc Lower"
sky_bridge_main                 = "Sky Bridge Main"
sky_bridge_east                 = "Sky Bridge East"
sky_bridge_east_lower           = "Sky Bridge East Lower"
sky_bridge_dark_area            = "Sky Bridge Dark Area"
sky_bridge_health_surge_room    = "Sky Bridge Health Surge Room"
sky_bridge_regen_up_ledge       = "Sky Bridge Regen Up Ledge"
sky_bridge_slide_area           = "Sky Bridge Slide Area"

# Area 3: Northern Tundra
northern_tundra_region          = "Northern Tundra"
snowland_east                   = "Snowland East"
snowland_mid                    = "Snowland Mid"
snowland_quick_barrette_room    = "Snowland Quick Barrette Room"
snowland_rita                   = "Snowland Rita"
snowland_lake                   = "Snowland Lake"
snowland_west                   = "Snowland West"
snowland_spike_room             = "Snowland Spike Room"
snowland_evernight_entrance     = "Snowland Evernight Entrance"
snowland_christmas_tree         = "Snowland Christmas Tree"
palace_warp_level_1_2           = "Palace Warp Level 1 2"
palace_attack_up_tunnel         = "Palace Attack Up Tunnel"
palace_level_3                  = "Palace Level 3"
palace_level_4                  = "Palace Level 4"
palace_level_5                  = "Palace Level 5"
icy_summit_main                 = "Icy Summit Main"
icy_summit_upper                = "Icy Summit Upper"
icy_summit_nixie                = "Icy Summit Nixie"
aquarium_top_entrance           = "Aquarium Top Entrance"
aquarium_mid_west               = "Aquarium Mid West"
aquarium_below_water_tower      = "Aquarium Below Water Tower"
aquarium_water_tower            = "Aquarium Water Tower"
aquarium_west_darkness          = "Aquarium West Darkness"
aquarium_west_lower             = "Aquarium West Lower"
aquarium_seana                  = "Aquarium Seana"
aquarium_mid_east               = "Aquarium Mid East"
aquarium_east                   = "Aquarium East"
aquarium_orb_slide_maze         = "Aquarium Orb Slide Maze"
aquarium_bomb_walled_area       = "Aquarium Bomb Walled Area"
aquarium_beach_entrance         = "Aquarium Beach Entrance"

# Area 4: Eastern Highlands
eastern_highlands_region        = "Eastern Highlands"
riverbank_main_level1           = "Riverbank Main Level1"
riverbank_level2                = "Riverbank Level2"
riverbank_level3                = "Riverbank Level3"
riverbank_lower_left            = "Riverbank Lower Left"
riverbank_lower_mid             = "Riverbank Lower Mid"
riverbank_lower_right           = "Riverbank Lower Right"
riverbank_lower_health_up_room  = "Riverbank Lower Health Up Room"
riverbank_pack_up_room          = "Riverbank Pack Up Room"
riverbank_lower_forest_entrance = "Riverbank Lower Forest Entrance"
riverbank_underground           = "Riverbank Underground"
evernight_west_entrance         = "Evernight West Entrance"
evernight_northwest             = "Evernight Northwest"
evernight_spike_barrier_room    = "Evernight Spike Barrier Room"
evernight_warp                  = "Evernight Warp"
evernight_saya                  = "Evernight Saya"
evernight_corridor_below_saya   = "Evernight Corridor Below Saya"
evernight_east_of_warp          = "Evernight East Of Warp"
evernight_lower                 = "Evernight Lower"
lab_entrance                    = "Lab Entrance"
lab_mid                         = "Lab Mid"
lab_west                        = "Lab West"
lab_east                        = "Lab East"
lab_east_atk_up_room           = "Lab East Atk Up Room"
lab_east_pack_up_room           = "Lab East Pack Up Room"
lab_sliding_powder_room         = "Lab Sliding Powder Room"
lab_computer_room               = "Lab Computer Room"

# Area 5: Rabi Rabi Town
rabi_rabi_town_region           = "Rabi Rabi Town"
town_main                       = "Town Main"
town_shop                       = "Town Shop"

# Area 6: Plurkwood
plurkwood_region                = "Plurkwood"
plurkwood_main                  = "Plurkwood Main"

# Area 7: Subterranean Area
subterranean_area_region        = "Subterranean Area"
volcanic_main                   = "Volcanic Main"
volcanic_beach_entrance         = "Volcanic Beach Entrance"
hall_of_memories                = "Hall Of Memories"

# Area 8: Warp Destination
warp_destination_region         = "Warp Destination"
warp_destination_outside        = "Warp Destination Outside"
warp_destination_hospital       = "Warp Destination Hospital"

# Area 9: System Interior
system_interior_region          = "System Interior"
system_interior_main            = "System Interior Main"
sysint2_start                   = "Sysint2 Start"
sysint2_egg_room                = "Sysint2 Egg Room"
sysint2_end                     = "Sysint2 End"

# Extra
unreachable_location            = "Unreachable Location"

# Items
# Area 0: Southern Woodland
nature_orb                   = "Nature Orb"
pack_up_forest_night         = "Pack Up Forest Night"
hp_up_west_spectral          = "Hp Up West Spectral"
atk_up_forest_night          = "Atk Up Forest Night"
pack_up_spectral             = "Pack Up Spectral"
mp_up_cave                   = "Mp Up Cave"
hp_up_cave                   = "Hp Up Cave"
blessed                      = "Blessed"
toxic_strike                 = "Toxic Strike"
piko_hammer                  = "Piko Hammer"
mp_up_forest_cave            = "Mp Up Forest Cave"
tough_skin                   = "Tough Skin"
regen_up_cave                = "Regen Up Cave"
hp_up_north_forest           = "Hp Up North Forest"
wall_jump                    = "Wall Jump"
regen_up_mid_forest          = "Regen Up Mid Forest"
mp_up_mid_spectral           = "Mp Up Mid Spectral"
hp_up_mid_spectral           = "Hp Up Mid Spectral"
carrot_bomb                  = "Carrot Bomb"
def_trade                    = "Def Trade"
light_orb                    = "Light Orb"
hp_up_forest_post_cocoa      = "Hp Up Forest Post Cocoa"
charge_ring                  = "Charge Ring"
arm_strength                 = "Arm Strength"
regen_up_east_forest         = "Regen Up East Forest"
mana_wager                   = "Mana Wager"
mp_up_east_forest            = "Mp Up East Forest"
pack_up_east_forest          = "Pack Up East Forest"
mp_up_cicini                 = "Mp Up Cicini"
mp_up_northeast_forest       = "Mp Up Northeast Forest"

# Area 1: Western Coast
survival                     = "Survival"
health_wager                 = "Health Wager"
atk_up_beach_cave            = "Atk Up Beach Cave"
mp_up_graveyard_warp         = "Mp Up Graveyard Warp"
hp_up_graveyard              = "Hp Up Graveyard"
sunny_beam                   = "Sunny Beam"
mp_up_upper_graveyard        = "Mp Up Upper Graveyard"
auto_earrings                = "Auto Earrings"
auto_trigger                 = "Auto Trigger"
health_plus                  = "Health Plus"
mp_up_pyramid_dark_room      = "Mp Up Pyramid Dark Room"
crisis_boost                 = "Crisis Boost"
atk_up_graveyard             = "Atk Up Graveyard"
hp_up_inner_pyramid          = "Hp Up Inner Pyramid"
hp_up_beach                  = "Hp Up Beach"
atk_up_pyramid               = "Atk Up Pyramid"
pack_up_pyramid              = "Pack Up Pyramid"
armored                      = "Armored"
chaos_rod                    = "Chaos Rod"
pack_up_beach                = "Pack Up Beach"
top_form                     = "Top Form"
hp_up_pyramid_entrance       = "Hp Up Pyramid Entrance"
hitbox_down                  = "Hitbox Down"
mp_up_pyramid_bombblock_room = "Mp Up Pyramid Bombblock Room"
air_dash                     = "Air Dash"
regen_up_pyramid             = "Regen Up Pyramid"
pure_love                    = "Pure Love"
mp_up_beach_tunnel           = "Mp Up Beach Tunnel"
hourglass                    = "Hourglass"
hp_up_sky_island             = "Hp Up Sky Island"
pack_up_sky_island           = "Pack Up Sky Island"
regen_up_sky_island          = "Regen Up Sky Island"
mp_up_beach_pillar           = "Mp Up Beach Pillar"

# Area 2: Island Core
def_grow                     = "Def Grow"
atk_up_park                  = "Atk Up Park"
atk_trade                    = "Atk Trade"
hp_up_park                   = "Hp Up Park"
rabi_slippers                = "Rabi Slippers"
regen_up_park                = "Regen Up Park"
health_surge                 = "Health Surge"
mp_up_sky_bridge             = "Mp Up Sky Bridge"
mp_up_uprprc_hq              = "Mp Up Uprprc Hq"
mp_up_park                   = "Mp Up Park"
hex_cancel                   = "Hex Cancel"
hp_up_sky_bridge             = "Hp Up Sky Bridge"
pack_up_sky_bridge           = "Pack Up Sky Bridge"
regen_up_sky_bridge          = "Regen Up Sky Bridge"
lucky_seven                  = "Lucky Seven"
atk_up_vanilla               = "Atk Up Vanilla"
hammer_wave                  = "Hammer Wave"
atk_up_west_ravine           = "Atk Up West Ravine"
hp_up_south_ravine           = "Hp Up South Ravine"
atk_up_north_ravine          = "Atk Up North Ravine"
hp_up_mid_ravine             = "Hp Up Mid Ravine"
mp_up_ravine                 = "Mp Up Ravine"
regen_up_ravine              = "Regen Up Ravine"
mana_surge                   = "Mana Surge"

# Area 3: Northern Tundra
hp_up_palace                 = "Hp Up Palace"
water_orb                    = "Water Orb"
hp_up_west_aquarium          = "Hp Up West Aquarium"
mana_plus                    = "Mana Plus"
atk_up_palace                = "Atk Up Palace"
atk_up_snowland              = "Atk Up Snowland"
regen_up_palace              = "Regen Up Palace"
stamina_plus                 = "Stamina Plus"
mp_up_palace                 = "Mp Up Palace"
self_defense                 = "Self Defense"
hp_up_upper_aquarium         = "Hp Up Upper Aquarium"
gold_carrot                  = "Gold Carrot"
atk_up_upper_aquarium        = "Atk Up Upper Aquarium"
pack_up_icy_summit           = "Pack Up Icy Summit"
atk_up_icy_summit            = "Atk Up Icy Summit"
atk_up_mid_aquarium          = "Atk Up Mid Aquarium"
mp_up_icy_summit             = "Mp Up Icy Summit"
mp_up_snowland               = "Mp Up Snowland"
quick_barrette               = "Quick Barrette"
hp_up_icy_summit             = "Hp Up Icy Summit"
super_carrot                 = "Super Carrot"
regen_up_snowland_water      = "Regen Up Snowland Water"
mp_up_aquarium               = "Mp Up Aquarium"
hp_up_snowland               = "Hp Up Snowland"
carrot_boost                 = "Carrot Boost"
regen_up_aquarium            = "Regen Up Aquarium"
pack_up_aquarium             = "Pack Up Aquarium"

# Area 4: Eastern Highlands
regen_up_northwest_riverbank = "Regen Up Northwest Riverbank"
pack_up_riverbank            = "Pack Up Riverbank"
mp_up_southwest_riverbank    = "Mp Up Southwest Riverbank"
atk_grow                     = "Atk Grow"
regen_up_south_riverbank     = "Regen Up South Riverbank"
atk_up_riverbank_pit         = "Atk Up Riverbank Pit"
bunny_whirl                  = "Bunny Whirl"
explode_shot                 = "Explode Shot"
mp_up_mid_riverbank          = "Mp Up Mid Riverbank"
atk_up_east_riverbank        = "Atk Up East Riverbank"
spike_barrier                = "Spike Barrier"
frame_cancel                 = "Frame Cancel"
hp_up_lab_slide_tunnel       = "Hp Up Lab Slide Tunnel"
mp_up_lab                    = "Mp Up Lab"
hp_up_riverbank              = "Hp Up Riverbank"
mp_up_evernight              = "Mp Up Evernight"
hp_up_evernight              = "Hp Up Evernight"
hp_up_lab_pit                = "Hp Up Lab Pit"
sliding_powder               = "Sliding Powder"
atk_up_evernight_uprprc      = "Atk Up Evernight Uprprc"
cashback                     = "Cashback"
plus_necklace                = "Plus Necklace"
weaken                       = "Weaken"
atk_up_lab_computer          = "Atk Up Lab Computer"
pack_up_south_evernight      = "Pack Up South Evernight"
pack_up_north_evernight      = "Pack Up North Evernight"
regen_up_evernight           = "Regen Up Evernight"
atk_up_evernight             = "Atk Up Evernight"
atk_up_east_lab              = "Atk Up East Lab"
pack_up_lab                  = "Pack Up Lab"
hammer_roll                  = "Hammer Roll"
pbpb_box                     = "Pbpb Box"

# Area 5: Rabi Rabi Town
ribbon_badge                 = "Ribbon Badge"
erina_badge                  = "Erina Badge"

# Area 6: Plurkwood
# Nothing, as P Hairpin is a part of gift item shuffle

# Area 7: Subterranean Area
hp_up_volcanic               = "Hp Up Volcanic"
carrot_shooter               = "Carrot Shooter"
fire_orb                     = "Fire Orb"
pack_up_volcanic             = "Pack Up Volcanic"

# Area 8: Warp Destination
# Nothing, here for completeness

# Area 9: System Interior
regen_up_cyberspace          = "Regen Up Cyberspace"
pack_up_cyberspace           = "Pack Up Cyberspace"
cyber_flower                 = "Cyber Flower"
air_jump                     = "Air Jump"
hp_up_cyberspace             = "Hp Up Cyberspace"
atk_up_cyberspace            = "Atk Up Cyberspace"
mp_up_cyberspace             = "Mp Up Cyberspace"

# Shufflable Gift Items
shufflable_gift_items        = "Gift Items"
p_hairpin                    = "P Hairpin"
speed_boost                  = "Speed Boost"
bunny_strike                 = "Bunny Strike"

# Eggs
# Area 0: Southern Woodland Eggs
egg_rumi                     = "Egg Rumi"
egg_forestnight_aruraune     = "Egg Forestnight Aruraune"
egg_spectral_west            = "Egg Spectral West"
egg_cave_under_hammer        = "Egg Cave Under Hammer"
egg_forestnight_east         = "Egg Forestnight East"
egg_spectral_slide           = "Egg Spectral Slide"
egg_cave_cocoa               = "Egg Cave Cocoa"
egg_forest_ne_ledge          = "Egg Forest Ne Ledge"
egg_forest_ne_pedestal       = "Egg Forest Ne Pedestal"

# Area 1: Western Coast Eggs
egg_halloween_west           = "Egg Halloween West"
egg_beach_to_aquarium        = "Egg Beach To Aquarium"
egg_halloween_mid            = "Egg Halloween Mid"
egg_halloween_sw_slide       = "Egg Halloween Sw Slide"
egg_halloween_near_boss      = "Egg Halloween Near Boss"
egg_halloween_warp_zone      = "Egg Halloween Warp Zone"
egg_graveyard_near_library   = "Egg Graveyard Near Library"
egg_halloween_cicini_room    = "Egg Halloween Cicini Room"
egg_library                  = "Egg Library"
egg_pyramid_beach            = "Egg Pyramid Beach"
egg_halloween_left_pillar    = "Egg Halloween Left Pillar"
egg_halloween_right_pillar   = "Egg Halloween Right Pillar"
egg_pyramid_lower            = "Egg Pyramid Lower"
egg_halloween_past_pillars1  = "Egg Halloween Past Pillars1"
egg_halloween_past_pillars2  = "Egg Halloween Past Pillars2"
egg_sky_town                 = "Egg Sky Town"

# Area 2: Island Core Eggs
egg_park_spikes              = "Egg Park Spikes"
egg_park_green_kotri         = "Egg Park Green Kotri"
egg_uprprc_base              = "Egg Uprprc Base"
egg_sky_bridge_above_warp    = "Egg Sky Bridge Above Warp"
egg_sky_bridge_warp          = "Egg Sky Bridge Warp"
egg_sky_bridge_by_vanilla    = "Egg Sky Bridge By Vanilla"
egg_ravine_above_chocolate   = "Egg Ravine Above Chocolate"
egg_ravine_mid               = "Egg Ravine Mid"

# Area 3: Northern Tundra Eggs
egg_snowland_to_evernight    = "Egg Snowland To Evernight"
egg_palace_bridge            = "Egg Palace Bridge"
egg_aquarium                 = "Egg Aquarium"
egg_palace_wall              = "Egg Palace Wall"
egg_snowland_warp            = "Egg Snowland Warp"
egg_icy_summit_nixie         = "Egg Icy Summit Nixie"
egg_snowland_spikes_room     = "Egg Snowland Spikes Room"
egg_icy_summit_warp          = "Egg Icy Summit Warp"
egg_snowland_lake            = "Egg Snowland Lake"

# Area 4: Eastern Highlands Eggs
egg_riverbank_spider_spike   = "Egg Riverbank Spider Spike"
egg_riverbank_wall           = "Egg Riverbank Wall"
egg_lab                      = "Egg Lab"
egg_lab_entrance             = "Egg Lab Entrance"
egg_evernight_mid            = "Egg Evernight Mid"
egg_evernight_saya           = "Egg Evernight Saya"

# Area 5: Rabi Rabi Town Eggs
egg_town                     = "Egg Town"

# Area 6: Plurkwood Eggs
egg_plurk_cats               = "Egg Plurk Cats"
egg_plurk_cave               = "Egg Plurk Cave"
egg_plurk_east               = "Egg Plurk East"

# Area 7: Subterranean Area Eggs
egg_volcanic_bomb_bunnies    = "Egg Volcanic Bomb Bunnies"
egg_memories_sysint          = "Egg Memories Sysint"
egg_memories_cars_room       = "Egg Memories Cars Room"
egg_memories_ravine          = "Egg Memories Ravine"
egg_volcanic_fire_orb        = "Egg Volcanic Fire Orb"
egg_volcanic_ne              = "Egg Volcanic Ne"
egg_volcanic_big_drop        = "Egg Volcanic Big Drop"

# Area 8: Warp Destination Eggs
egg_crespirit                = "Egg Crespirit"
egg_hospital_wall            = "Egg Hospital Wall"
egg_hospital_box             = "Egg Hospital Box"

# Area 9: System Interior Eggs
egg_sysint2                  = "Egg Sysint2"
egg_sysint2_long_jump        = "Egg Sysint2 Long Jump"
egg_sysint1                  = "Egg Sysint1"

start_location_to_area_name = {
    forest_start: "Starting Forest",
    forest_warp: "Starting Forest",
    pyramid_warp_room: "Golden Pyramid",
    spectral_warp: "Spectral Cave",
    lab_mid: "Exotic Laboratory",
    volcanic_main: "Volcanic Caverns",
    town_main: "Rabi Rabi Town",
    aquarium_top_entrance: "Natural Aquarium",
    sky_bridge_main: "Sky-High Bridge",
    snowland_rita: "Aurora Snow Land",
    evernight_warp: "Evernight Peak",
    riverbank_main_level1: "Golden Riverbank",
    graveyard_main: "Floating Graveyard",
    hall_of_memories: "Hall of Memories",
    forgotten_cave_2: "Forgotten Cave 2",
    beach_main: "Rabi Rabi Beach",
    park_warp: "Rabi Rabi Park",
    palace_warp_level_1_2: "Aurora Palace",
    ravine_upper_east: "Rabi Rabi Ravine",
    icy_summit_main: "Icy Summit",
    sky_island_upper: "Sky Island Town"
}