
# Regions
# Area 0: Southern Woodland
southern_woodland_region        = "SOUTHERN_WOODLAND_REGION"
forest_start                    = "FOREST_START"
forest_warp                     = "FOREST_WARP"
forest_east_above_spring        = "FOREST_EAST_ABOVE_SPRING"
forest_upper_east               = "FOREST_UPPER_EAST"
forest_upper_riverbank_exit     = "FOREST_UPPER_RIVERBANK_EXIT"
forest_lower_riverbank_exit     = "FOREST_LOWER_RIVERBANK_EXIT"
forest_light_orb_room           = "FOREST_LIGHT_ORB_ROOM"
forest_upper_east_egg_ledge     = "FOREST_UPPER_EAST_EGG_LEDGE"
forest_cocoa_room               = "FOREST_COCOA_ROOM"
forest_north_hp_up_room         = "FOREST_NORTH_HP_UP_ROOM"
forest_night_toxic_strike       = "FOREST_NIGHT_TOXIC_STRIKE"
forest_night_north_east         = "FOREST_NIGHT_NORTH_EAST"
forest_night_west               = "FOREST_NIGHT_WEST"
forest_night_atk_up_room        = "FOREST_NIGHT_ATK_UP_ROOM"
cave_entrance                   = "CAVE_ENTRANCE"
cave_west                       = "CAVE_WEST"
cave_cocoa                      = "CAVE_COCOA"
forgotten_cave_2                = "FORGOTTEN_CAVE_2"
spectral_upper                  = "SPECTRAL_UPPER"
spectral_mid                    = "SPECTRAL_MID"
spectral_west                   = "SPECTRAL_WEST"
spectral_gap_ledge              = "SPECTRAL_GAP_LEDGE"
spectral_west_egg_room          = "SPECTRAL_WEST_EGG_ROOM"
spectral_warp                   = "SPECTRAL_WARP"
spectral_cicini_ledge           = "SPECTRAL_CICINI_LEDGE"
spectral_cicini_room            = "SPECTRAL_CICINI_ROOM"

# Area 1: Western Coast
western_coast_region            = "WESTERN_COAST_REGION"
beach_main                      = "BEACH_MAIN"
beach_forest_entrance           = "BEACH_FOREST_ENTRANCE"
beach_underwater_entrance       = "BEACH_UNDERWATER_ENTRANCE"
beach_volcanic_entrance         = "BEACH_VOLCANIC_ENTRANCE"
pyramid_main                    = "PYRAMID_MAIN"
pyramid_hourglass_room          = "PYRAMID_HOURGLASS_ROOM"
pyramid_warp_room               = "PYRAMID_WARP_ROOM"
pyramid_southwest_room          = "PYRAMID_SOUTHWEST_ROOM"
pyramid_lower                   = "PYRAMID_LOWER"
pyramid_chaos_rod_room          = "PYRAMID_CHAOS_ROD_ROOM"
graveyard_top_of_bridge         = "GRAVEYARD_TOP_OF_BRIDGE"
graveyard_main                  = "GRAVEYARD_MAIN"
graveyard_kotri                 = "GRAVEYARD_KOTRI"
graveyard_upper                 = "GRAVEYARD_UPPER"
sky_island_main                 = "SKY_ISLAND_MAIN"
sky_island_air_dash_room        = "SKY_ISLAND_AIR_DASH_ROOM"
sky_island_upper                = "SKY_ISLAND_UPPER"
sky_island_oob                  = "SKY_ISLAND_OOB"
halloween_upper                 = "HALLOWEEN_UPPER"
halloween_dark_shaft            = "HALLOWEEN_DARK_SHAFT"
halloween_central               = "HALLOWEEN_CENTRAL"
halloween_flooded               = "HALLOWEEN_FLOODED"
halloween_pumpkin_hall          = "HALLOWEEN_PUMPKIN_HALL"
halloween_exit                  = "HALLOWEEN_EXIT"
halloween_past_pillars          = "HALLOWEEN_PAST_PILLARS"
library_outside                 = "LIBRARY_OUTSIDE"
library_entrance                = "LIBRARY_ENTRANCE"
library_bottom                  = "LIBRARY_BOTTOM"
library_alcove_ledge            = "LIBRARY_ALCOVE_LEDGE"
library_mid_lower               = "LIBRARY_MID_LOWER"
library_mid_upper               = "LIBRARY_MID_UPPER"
library_irisu                   = "LIBRARY_IRISU"
library_oob                     = "LIBRARY_OOB"

# Area 2: Island Core
island_core_region              = "ISLAND_CORE_REGION"
ravine_lower                    = "RAVINE_LOWER"
ravine_upper_east               = "RAVINE_UPPER_EAST"
ravine_upper_west               = "RAVINE_UPPER_WEST"
ravine_mana_surge               = "RAVINE_MANA_SURGE"
ravine_north_attack_up_room     = "RAVINE_NORTH_ATTACK_UP_ROOM"
ravine_chocolate                = "RAVINE_CHOCOLATE"
ravine_above_chocolate          = "RAVINE_ABOVE_CHOCOLATE"
ravine_town_entrance            = "RAVINE_TOWN_ENTRANCE"
ravine_beach_entrance           = "RAVINE_BEACH_ENTRANCE"
park_main                       = "PARK_MAIN"
park_warp                       = "PARK_WARP"
park_kotri                      = "PARK_KOTRI"
park_town_entrance              = "PARK_TOWN_ENTRANCE"
park_upper                      = "PARK_UPPER"
uprprc_base                     = "UPRPRC_BASE"
uprprc_lower                    = "UPRPRC_LOWER"
sky_bridge_main                 = "SKY_BRIDGE_MAIN"
sky_bridge_east                 = "SKY_BRIDGE_EAST"
sky_bridge_east_lower           = "SKY_BRIDGE_EAST_LOWER"
sky_bridge_dark_area            = "SKY_BRIDGE_DARK_AREA"
sky_bridge_health_surge_room    = "SKY_BRIDGE_HEALTH_SURGE_ROOM"
sky_bridge_regen_up_ledge       = "SKY_BRIDGE_REGEN_UP_LEDGE"
sky_bridge_slide_area           = "SKY_BRIDGE_SLIDE_AREA"

# Area 3: Northern Tundra
northern_tundra_region          = "NORTHERN_TUNDRA_REGION"
snowland_east                   = "SNOWLAND_EAST"
snowland_mid                    = "SNOWLAND_MID"
snowland_quick_barrette_room    = "SNOWLAND_QUICK_BARRETTE_ROOM"
snowland_rita                   = "SNOWLAND_RITA"
snowland_lake                   = "SNOWLAND_LAKE"
snowland_west                   = "SNOWLAND_WEST"
snowland_spike_room             = "SNOWLAND_SPIKE_ROOM"
snowland_evernight_entrance     = "SNOWLAND_EVERNIGHT_ENTRANCE"
snowland_christmas_tree         = "SNOWLAND_CHRISTMAS_TREE"
palace_warp_level_1_2           = "PALACE_WARP_LEVEL_1_2"
palace_attack_up_tunnel         = "PALACE_ATTACK_UP_TUNNEL"
palace_level_3                  = "PALACE_LEVEL_3"
palace_level_4                  = "PALACE_LEVEL_4"
palace_level_5                  = "PALACE_LEVEL_5"
icy_summit_main                 = "ICY_SUMMIT_MAIN"
icy_summit_upper                = "ICY_SUMMIT_UPPER"
icy_summit_nixie                = "ICY_SUMMIT_NIXIE"
aquarium_top_entrance           = "AQUARIUM_TOP_ENTRANCE"
aquarium_mid_west               = "AQUARIUM_MID_WEST"
aquarium_below_water_tower      = "AQUARIUM_BELOW_WATER_TOWER"
aquarium_water_tower            = "AQUARIUM_WATER_TOWER"
aquarium_west_darkness          = "AQUARIUM_WEST_DARKNESS"
aquarium_west_lower             = "AQUARIUM_WEST_LOWER"
aquarium_seana                  = "AQUARIUM_SEANA"
aquarium_mid_east               = "AQUARIUM_MID_EAST"
aquarium_east                   = "AQUARIUM_EAST"
aquarium_orb_slide_maze         = "AQUARIUM_ORB_SLIDE_MAZE"
aquarium_bomb_walled_area       = "AQUARIUM_BOMB_WALLED_AREA"
aquarium_beach_entrance         = "AQUARIUM_BEACH_ENTRANCE"

# Area 4: Eastern Highlands
eastern_highlands_region        = "EASTERN_HIGHLANDS_REGION"
riverbank_main_level1           = "RIVERBANK_MAIN_LEVEL1"
riverbank_level2                = "RIVERBANK_LEVEL2"
riverbank_level3                = "RIVERBANK_LEVEL3"
riverbank_lower_left            = "RIVERBANK_LOWER_LEFT"
riverbank_lower_mid             = "RIVERBANK_LOWER_MID"
riverbank_lower_right           = "RIVERBANK_LOWER_RIGHT"
riverbank_lower_health_up_room  = "RIVERBANK_LOWER_HEALTH_UP_ROOM"
riverbank_pack_up_room          = "RIVERBANK_PACK_UP_ROOM"
riverbank_lower_forest_entrance = "RIVERBANK_LOWER_FOREST_ENTRANCE"
riverbank_underground           = "RIVERBANK_UNDERGROUND"
evernight_west_entrance         = "EVERNIGHT_WEST_ENTRANCE"
evernight_northwest             = "EVERNIGHT_NORTHWEST"
evernight_spike_barrier_room    = "EVERNIGHT_SPIKE_BARRIER_ROOM"
evernight_warp                  = "EVERNIGHT_WARP"
evernight_saya                  = "EVERNIGHT_SAYA"
evernight_corridor_below_saya   = "EVERNIGHT_CORRIDOR_BELOW_SAYA"
evernight_east_of_warp          = "EVERNIGHT_EAST_OF_WARP"
evernight_lower                 = "EVERNIGHT_LOWER"
lab_entrance                    = "LAB_ENTRANCE"
lab_mid                         = "LAB_MID"
lab_west                        = "LAB_WEST"
lab_east                        = "LAB_EAST"
lab_east_atk_up_room           = "LAB_EAST_ATK_UP_ROOM"
lab_east_pack_up_room           = "LAB_EAST_PACK_UP_ROOM"
lab_sliding_powder_room         = "LAB_SLIDING_POWDER_ROOM"
lab_computer_room               = "LAB_COMPUTER_ROOM"

# Area 5: Rabi Rabi Town
rabi_rabi_town_region           = "RABI_RABI_TOWN_REGION"
town_main                       = "TOWN_MAIN"
town_shop                       = "TOWN_SHOP"

# Area 6: Plurkwood
plurkwood_region                = "PLURKWOOD_REGION"
plurkwood_main                  = "PLURKWOOD_MAIN"

# Area 7: Subterranean Area
subterranean_area_region        = "SUBTERRANEAN_AREA_REGION"
volcanic_main                   = "VOLCANIC_MAIN"
volcanic_beach_entrance         = "VOLCANIC_BEACH_ENTRANCE"
hall_of_memories                = "HALL_OF_MEMORIES"

# Area 8: Warp Destination
warp_destination_region         = "WARP_DESTINATION_REGION"
warp_destination_outside        = "WARP_DESTINATION_OUTSIDE"
warp_destination_hospital       = "WARP_DESTINATION_HOSPITAL"

# Area 9: System Interior
system_interior_region          = "SYSTEM_INTERIOR_REGION"
system_interior_main            = "SYSTEM_INTERIOR_MAIN"
sysint2_start                   = "SYSINT2_START"
sysint2_egg_room                = "SYSINT2_EGG_ROOM"
sysint2_end                     = "SYSINT2_END"

# Items
# Area 0: Southern Woodland
nature_orb                   = "NATURE_ORB"
pack_up_forest_night         = "PACK_UP_FOREST_NIGHT"
hp_up_west_spectral          = "HP_UP_WEST_SPECTRAL"
atk_up_forest_night          = "ATK_UP_FOREST_NIGHT"
pack_up_spectral             = "PACK_UP_SPECTRAL"
mp_up_cave                   = "MP_UP_CAVE"
hp_up_cave                   = "HP_UP_CAVE"
blessed                      = "BLESSED"
toxic_strike                 = "TOXIC_STRIKE"
piko_hammer                  = "PIKO_HAMMER"
mp_up_forest_cave            = "MP_UP_FOREST_CAVE"
tough_skin                   = "TOUGH_SKIN"
regen_up_cave                = "REGEN_UP_CAVE"
hp_up_north_forest           = "HP_UP_NORTH_FOREST"
wall_jump                    = "WALL_JUMP"
regen_up_mid_forest          = "REGEN_UP_MID_FOREST"
mp_up_mid_spectral           = "MP_UP_MID_SPECTRAL"
hp_up_mid_spectral           = "HP_UP_MID_SPECTRAL"
carrot_bomb                  = "CARROT_BOMB"
def_trade                    = "DEF_TRADE"
light_orb                    = "LIGHT_ORB"
hp_up_forest_post_cocoa      = "HP_UP_FOREST_POST_COCOA"
charge_ring                  = "CHARGE_RING"
arm_strength                 = "ARM_STRENGTH"
regen_up_east_forest         = "REGEN_UP_EAST_FOREST"
mana_wager                   = "MANA_WAGER"
mp_up_east_forest            = "MP_UP_EAST_FOREST"
pack_up_east_forest          = "PACK_UP_EAST_FOREST"
mp_up_cicini                 = "MP_UP_CICINI"
mp_up_northeast_forest       = "MP_UP_NORTHEAST_FOREST"

# Area 1: Western Coast
survival                     = "SURVIVAL"
health_wager                 = "HEALTH_WAGER"
atk_up_beach_cave            = "ATK_UP_BEACH_CAVE"
mp_up_graveyard_warp         = "MP_UP_GRAVEYARD_WARP"
hp_up_graveyard              = "HP_UP_GRAVEYARD"
sunny_beam                   = "SUNNY_BEAM"
mp_up_upper_graveyard        = "MP_UP_UPPER_GRAVEYARD"
auto_earrings                = "AUTO_EARRINGS"
auto_trigger                 = "AUTO_TRIGGER"
health_plus                  = "HEALTH_PLUS"
mp_up_pyramid_dark_room      = "MP_UP_PYRAMID_DARK_ROOM"
crisis_boost                 = "CRISIS_BOOST"
atk_up_graveyard             = "ATK_UP_GRAVEYARD"
hp_up_inner_pyramid          = "HP_UP_INNER_PYRAMID"
hp_up_beach                  = "HP_UP_BEACH"
atk_up_pyramid               = "ATK_UP_PYRAMID"
pack_up_pyramid              = "PACK_UP_PYRAMID"
armored                      = "ARMORED"
chaos_rod                    = "CHAOS_ROD"
pack_up_beach                = "PACK_UP_BEACH"
top_form                     = "TOP_FORM"
hp_up_pyramid_entrance       = "HP_UP_PYRAMID_ENTRANCE"
hitbox_down                  = "HITBOX_DOWN"
mp_up_pyramid_bombblock_room = "MP_UP_PYRAMID_BOMBBLOCK_ROOM"
air_dash                     = "AIR_DASH"
regen_up_pyramid             = "REGEN_UP_PYRAMID"
pure_love                    = "PURE_LOVE"
mp_up_beach_tunnel           = "MP_UP_BEACH_TUNNEL"
hourglass                    = "HOURGLASS"
hp_up_sky_island             = "HP_UP_SKY_ISLAND"
pack_up_sky_island           = "PACK_UP_SKY_ISLAND"
regen_up_sky_island          = "REGEN_UP_SKY_ISLAND"
mp_up_beach_pillar           = "MP_UP_BEACH_PILLAR"

# Area 2: Island Core
def_grow                     = "DEF_GROW"
atk_up_park                  = "ATK_UP_PARK"
atk_trade                    = "ATK_TRADE"
hp_up_park                   = "HP_UP_PARK"
rabi_slippers                = "RABI_SLIPPERS"
regen_up_park                = "REGEN_UP_PARK"
health_surge                 = "HEALTH_SURGE"
mp_up_sky_bridge             = "MP_UP_SKY_BRIDGE"
mp_up_uprprc_hq              = "MP_UP_UPRPRC_HQ"
mp_up_park                   = "MP_UP_PARK"
hex_cancel                   = "HEX_CANCEL"
hp_up_sky_bridge             = "HP_UP_SKY_BRIDGE"
pack_up_sky_bridge           = "PACK_UP_SKY_BRIDGE"
regen_up_sky_bridge          = "REGEN_UP_SKY_BRIDGE"
lucky_seven                  = "LUCKY_SEVEN"
atk_up_vanilla               = "ATK_UP_VANILLA"
hammer_wave                  = "HAMMER_WAVE"
atk_up_west_ravine           = "ATK_UP_WEST_RAVINE"
hp_up_south_ravine           = "HP_UP_SOUTH_RAVINE"
atk_up_north_ravine          = "ATK_UP_NORTH_RAVINE"
hp_up_mid_ravine             = "HP_UP_MID_RAVINE"
mp_up_ravine                 = "MP_UP_RAVINE"
regen_up_ravine              = "REGEN_UP_RAVINE"
mana_surge                   = "MANA_SURGE"

# Area 3: Northern Tundra
hp_up_palace                 = "HP_UP_PALACE"
water_orb                    = "WATER_ORB"
hp_up_west_aquarium          = "HP_UP_WEST_AQUARIUM"
mana_plus                    = "MANA_PLUS"
atk_up_palace                = "ATK_UP_PALACE"
atk_up_snowland              = "ATK_UP_SNOWLAND"
regen_up_palace              = "REGEN_UP_PALACE"
stamina_plus                 = "STAMINA_PLUS"
mp_up_palace                 = "MP_UP_PALACE"
self_defense                 = "SELF_DEFENSE"
hp_up_upper_aquarium         = "HP_UP_UPPER_AQUARIUM"
gold_carrot                  = "GOLD_CARROT"
atk_up_upper_aquarium        = "ATK_UP_UPPER_AQUARIUM"
pack_up_icy_summit           = "PACK_UP_ICY_SUMMIT"
atk_up_icy_summit            = "ATK_UP_ICY_SUMMIT"
atk_up_mid_aquarium          = "ATK_UP_MID_AQUARIUM"
mp_up_icy_summit             = "MP_UP_ICY_SUMMIT"
mp_up_snowland               = "MP_UP_SNOWLAND"
quick_barrette               = "QUICK_BARRETTE"
hp_up_icy_summit             = "HP_UP_ICY_SUMMIT"
super_carrot                 = "SUPER_CARROT"
regen_up_snowland_water      = "REGEN_UP_SNOWLAND_WATER"
mp_up_aquarium               = "MP_UP_AQUARIUM"
hp_up_snowland               = "HP_UP_SNOWLAND"
carrot_boost                 = "CARROT_BOOST"
regen_up_aquarium            = "REGEN_UP_AQUARIUM"
pack_up_aquarium             = "PACK_UP_AQUARIUM"

# Area 4: Eastern Highlands
regen_up_northwest_riverbank = "REGEN_UP_NORTHWEST_RIVERBANK"
pack_up_riverbank            = "PACK_UP_RIVERBANK"
mp_up_southwest_riverbank    = "MP_UP_SOUTHWEST_RIVERBANK"
atk_grow                     = "ATK_GROW"
regen_up_south_riverbank     = "REGEN_UP_SOUTH_RIVERBANK"
atk_up_riverbank_pit         = "ATK_UP_RIVERBANK_PIT"
bunny_whirl                  = "BUNNY_WHIRL"
explode_shot                 = "EXPLODE_SHOT"
mp_up_mid_riverbank          = "MP_UP_MID_RIVERBANK"
atk_up_east_riverbank        = "ATK_UP_EAST_RIVERBANK"
spike_barrier                = "SPIKE_BARRIER"
frame_cancel                 = "FRAME_CANCEL"
hp_up_lab_slide_tunnel       = "HP_UP_LAB_SLIDE_TUNNEL"
mp_up_lab                    = "MP_UP_LAB"
hp_up_riverbank              = "HP_UP_RIVERBANK"
mp_up_evernight              = "MP_UP_EVERNIGHT"
hp_up_evernight              = "HP_UP_EVERNIGHT"
hp_up_lab_pit                = "HP_UP_LAB_PIT"
sliding_powder               = "SLIDING_POWDER"
atk_up_evernight_uprprc      = "ATK_UP_EVERNIGHT_UPRPRC"
cashback                     = "CASHBACK"
plus_necklace                = "PLUS_NECKLACE"
weaken                       = "WEAKEN"
atk_up_lab_computer          = "ATK_UP_LAB_COMPUTER"
pack_up_south_evernight      = "PACK_UP_SOUTH_EVERNIGHT"
pack_up_north_evernight      = "PACK_UP_NORTH_EVERNIGHT"
regen_up_evernight           = "REGEN_UP_EVERNIGHT"
atk_up_evernight             = "ATK_UP_EVERNIGHT"
atk_up_east_lab              = "ATK_UP_EAST_LAB"
pack_up_lab                  = "PACK_UP_LAB"
hammer_roll                  = "HAMMER_ROLL"
pbpb_box                     = "PBPB_BOX"

# Area 5: Rabi Rabi Town
ribbon_badge                 = "RIBBON_BADGE"
erina_badge                  = "ERINA_BADGE"

# Area 6: Plurkwood
# Nothing, as P Hairpin is a part of gift item shuffle

# Area 7: Subterranean Area
hp_up_volcanic               = "HP_UP_VOLCANIC"
carrot_shooter               = "CARROT_SHOOTER"
fire_orb                     = "FIRE_ORB"
pack_up_volcanic             = "PACK_UP_VOLCANIC"

# Area 8: Warp Destination
# Nothing, here for completeness

# Area 9: System Interior
regen_up_cyberspace          = "REGEN_UP_CYBERSPACE"
pack_up_cyberspace           = "PACK_UP_CYBERSPACE"
cyber_flower                 = "CYBER_FLOWER"
air_jump                     = "AIR_JUMP"
hp_up_cyberspace             = "HP_UP_CYBERSPACE"
atk_up_cyberspace            = "ATK_UP_CYBERSPACE"
mp_up_cyberspace             = "MP_UP_CYBERSPACE"

# Shufflable Gift Items
shufflable_gift_items        = "SHUFFLABLE_GIFT_ITEMS"
p_hairpin                    = "P_HAIRPIN"
speed_boost                  = "SPEED_BOOST"
bunny_strike                 = "BUNNY_STRIKE"

# Eggs
# Area 0: Southern Woodland Eggs
egg_rumi                     = "EGG_RUMI"
egg_forestnight_aruraune     = "EGG_FORESTNIGHT_ARURAUNE"
egg_spectral_west            = "EGG_SPECTRAL_WEST"
egg_cave_under_hammer        = "EGG_CAVE_UNDER_HAMMER"
egg_forestnight_east         = "EGG_FORESTNIGHT_EAST"
egg_spectral_slide           = "EGG_SPECTRAL_SLIDE"
egg_cave_cocoa               = "EGG_CAVE_COCOA"
egg_forest_ne_ledge          = "EGG_FOREST_NE_LEDGE"
egg_forest_ne_pedestal       = "EGG_FOREST_NE_PEDESTAL"

# Area 1: Western Coast Eggs
egg_halloween_west           = "EGG_HALLOWEEN_WEST"
egg_beach_to_aquarium        = "EGG_BEACH_TO_AQUARIUM"
egg_halloween_mid            = "EGG_HALLOWEEN_MID"
egg_halloween_sw_slide       = "EGG_HALLOWEEN_SW_SLIDE"
egg_halloween_near_boss      = "EGG_HALLOWEEN_NEAR_BOSS"
egg_halloween_warp_zone      = "EGG_HALLOWEEN_WARP_ZONE"
egg_graveyard_near_library   = "EGG_GRAVEYARD_NEAR_LIBRARY"
egg_halloween_cicini_room    = "EGG_HALLOWEEN_CICINI_ROOM"
egg_library                  = "EGG_LIBRARY"
egg_pyramid_beach            = "EGG_PYRAMID_BEACH"
egg_halloween_left_pillar    = "EGG_HALLOWEEN_LEFT_PILLAR"
egg_halloween_right_pillar   = "EGG_HALLOWEEN_RIGHT_PILLAR"
egg_pyramid_lower            = "EGG_PYRAMID_LOWER"
egg_halloween_past_pillars1  = "EGG_HALLOWEEN_PAST_PILLARS1"
egg_halloween_past_pillars2  = "EGG_HALLOWEEN_PAST_PILLARS2"
egg_sky_town                 = "EGG_SKY_TOWN"

# Area 2: Island Core Eggs
egg_park_spikes              = "EGG_PARK_SPIKES"
egg_park_green_kotri         = "EGG_PARK_GREEN_KOTRI"
egg_uprprc_base              = "EGG_UPRPRC_BASE"
egg_sky_bridge_above_warp    = "EGG_SKY_BRIDGE_ABOVE_WARP"
egg_sky_bridge_warp          = "EGG_SKY_BRIDGE_WARP"
egg_sky_bridge_by_vanilla    = "EGG_SKY_BRIDGE_BY_VANILLA"
egg_ravine_above_chocolate   = "EGG_RAVINE_ABOVE_CHOCOLATE"
egg_ravine_mid               = "EGG_RAVINE_MID"

# Area 3: Northern Tundra Eggs
egg_snowland_to_evernight    = "EGG_SNOWLAND_TO_EVERNIGHT"
egg_palace_bridge            = "EGG_PALACE_BRIDGE"
egg_aquarium                 = "EGG_AQUARIUM"
egg_palace_wall              = "EGG_PALACE_WALL"
egg_snowland_warp            = "EGG_SNOWLAND_WARP"
egg_icy_summit_nixie         = "EGG_ICY_SUMMIT_NIXIE"
egg_snowland_spikes_room     = "EGG_SNOWLAND_SPIKES_ROOM"
egg_icy_summit_warp          = "EGG_ICY_SUMMIT_WARP"
egg_snowland_lake            = "EGG_SNOWLAND_LAKE"

# Area 4: Eastern Highlands Eggs
egg_riverbank_spider_spike   = "EGG_RIVERBANK_SPIDER_SPIKE"
egg_riverbank_wall           = "EGG_RIVERBANK_WALL"
egg_lab                      = "EGG_LAB"
egg_lab_entrance             = "EGG_LAB_ENTRANCE"
egg_evernight_mid            = "EGG_EVERNIGHT_MID"
egg_evernight_saya           = "EGG_EVERNIGHT_SAYA"

# Area 5: Rabi Rabi Town Eggs
egg_town                     = "EGG_TOWN"

# Area 6: Plurkwood Eggs
egg_plurk_cats               = "EGG_PLURK_CATS"
egg_plurk_cave               = "EGG_PLURK_CAVE"
egg_plurk_east               = "EGG_PLURK_EAST"

# Area 7: Subterranean Area Eggs
egg_volcanic_bomb_bunnies    = "EGG_VOLCANIC_BOMB_BUNNIES"
egg_memories_sysint          = "EGG_MEMORIES_SYSINT"
egg_memories_cars_room       = "EGG_MEMORIES_CARS_ROOM"
egg_memories_ravine          = "EGG_MEMORIES_RAVINE"
egg_volcanic_fire_orb        = "EGG_VOLCANIC_FIRE_ORB"
egg_volcanic_ne              = "EGG_VOLCANIC_NE"
egg_volcanic_big_drop        = "EGG_VOLCANIC_BIG_DROP"

# Area 8: Warp Destination Eggs
egg_crespirit                = "EGG_CRESPIRIT"
egg_hospital_wall            = "EGG_HOSPITAL_WALL"
egg_hospital_box             = "EGG_HOSPITAL_BOX"

# Area 9: System Interior Eggs
egg_sysint2                  = "EGG_SYSINT2"
egg_sysint2_long_jump        = "EGG_SYSINT2_LONG_JUMP"
egg_sysint1                  = "EGG_SYSINT1"